FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

COPY requirements.txt .

# Install dependencies (including pydantic-settings, fastapi, etc.)
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port your FastAPI application
EXPOSE 5050

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5050"]